import { listEmployeeRuntimeBindingsSync } from "@agent-space/db";
import { type AgentChannelMemberAccess, type ActiveEmployee, type AgentSpaceState } from "@agent-space/domain/workspace";
export declare function listActiveEmployeesSync(): ActiveEmployee[];
export declare function listEmployeeRuntimeBindingsForWorkspaceSync(workspaceId?: string): ReturnType<typeof listEmployeeRuntimeBindingsSync>;
export declare function listEmployeeSkillIdsMapSync(workspaceId?: string): Map<string, string[]>;
export declare function listEmployeeSkillIdsByAgentIdMapSync(workspaceId?: string): Map<string, string[]>;
export declare function listEmployeeSkillIdsSync(employeeName: string, workspaceId?: string): string[];
export declare function buildLegacyAgentIdForEmployeeName(employeeName: string): string;
export declare function bindEmployeeRuntimeSync(employeeName: string, runtimeId: string, workspaceId?: string, actorUserId?: string): AgentSpaceState;
export declare function unbindEmployeeRuntimeSync(employeeName: string, workspaceId?: string): AgentSpaceState;
export declare function deleteEmployeeSync(employeeName: string, workspaceId?: string): AgentSpaceState;
export declare function updateEmployeeInstructionsSync(employeeName: string, instructions: string, workspaceId?: string): AgentSpaceState;
export declare function updateEmployeeRemarkNameSync(employeeName: string, remarkName: string, workspaceId?: string): AgentSpaceState;
export declare function createEmployeeSync(input: {
    name: string;
    role?: string;
    remarkName?: string;
    summary?: string;
    traits?: string[];
    fit?: string;
    origin?: string;
    active?: boolean;
    instructions?: string;
    skillIds?: string[];
    ownerUserId?: string;
    channelMemberAccess?: AgentChannelMemberAccess;
}, workspaceId?: string): AgentSpaceState;
export declare function setEmployeeChannelMemberAccessSync(employeeName: string, channelMemberAccess: AgentChannelMemberAccess, workspaceId?: string): AgentSpaceState;
export declare function setEmployeeSkillIdsSync(employeeName: string, skillIds: string[], workspaceId?: string): AgentSpaceState;
