import type { StoredWorkspaceRecord } from "./types.ts";
export type HardDeleteWorkspaceResult = {
    deletedWorkspace: boolean;
    removedWorkspaceRows: number;
    removedWorkspaceSnapshotRows: number;
    removedMembershipRows: number;
    removedInvitationRows: number;
    removedGoogleOAuthCredentialRows: number;
    removedAgentGoogleWorkspaceDelegationRows: number;
    removedChannelRows: number;
    removedEmployeeRows: number;
    removedTaskRows: number;
    removedDaemonRows: number;
    removedDaemonTokenRows: number;
    removedRuntimeRows: number;
    removedRuntimeDisplayNameRows: number;
    removedRuntimeGrantRows: number;
    removedDocumentAgentAccessRows: number;
    removedDocumentPermissionRequestRows: number;
    removedAgentAccessRequestRows: number;
    removedKnowledgeProposalRows: number;
    removedAgentForkInvitationRows: number;
    removedAgentForkSnapshotRows: number;
    removedNotificationRows: number;
    removedBindingRows: number;
    removedAgentRouterProviderSessionRows: number;
    removedAgentTaskAttemptRows: number;
    removedAgentRouterEventRows: number;
    removedAgentRouterContextSnapshotRows: number;
    removedAgentRouterSessionRows: number;
    removedQueuedTaskRows: number;
    removedTaskMessageRows: number;
    removedTokenUsageRows: number;
    removedSkillRows: number;
    removedAgentSkillRows: number;
    removedKnowledgeAssignmentPolicyRows: number;
    removedAgentKnowledgePageRows: number;
    removedSkillImportEventRows: number;
    removedBudgetRows: number;
};
export declare function createWorkspaceSync(params: {
    name: string;
    createdBy: string;
    id?: string;
    slug?: string;
}): StoredWorkspaceRecord;
export declare function readWorkspaceSync(idOrSlug: string): StoredWorkspaceRecord | null;
export declare function listWorkspacesSync(): StoredWorkspaceRecord[];
export declare function readWorkspaceByJoinCodeSync(joinCode: string): StoredWorkspaceRecord | null;
export declare function rotateWorkspaceJoinCodeSync(input: {
    workspaceId: string;
    updatedBy: string;
}): StoredWorkspaceRecord;
export declare function ensureWorkspaceJoinCodesSync(): number;
export declare function updateWorkspaceSync(id: string, patch: Partial<Pick<StoredWorkspaceRecord, "name" | "slug">>): void;
export declare function archiveWorkspaceSync(id: string): void;
export declare function hardDeleteWorkspaceSync(id: string): HardDeleteWorkspaceResult;
