import type { AgentSpaceState, ChannelDocument, ChannelDocumentEditorType, ChannelDocumentExternalProvider, ChannelDocumentJsonContent, ChannelDocumentKind, ChannelDocumentStorageMode, ChannelDocumentTriggerType, ChannelDocumentVersion, ExternalSheetOperationRun } from "@agent-space/domain/workspace";
export declare function buildChannelDocumentRecord(input: {
    id: string;
    channelName: string;
    title: string;
    kind?: ChannelDocumentKind;
    storageMode?: ChannelDocumentStorageMode;
    linkedTableId?: string;
    externalProvider?: ChannelDocumentExternalProvider;
    externalFileId?: string;
    externalUrl?: string;
    externalRevisionId?: string;
    currentVersionId: string;
    summary: string;
    externalSyncStatus?: ChannelDocument["externalSyncStatus"];
    externalMimeType?: string;
    externalUpdatedAt?: string;
    lastEditorType: ChannelDocumentEditorType;
    createdBy: string;
    updatedBy: string;
    createdAt: string;
    updatedAt: string;
    existingDocuments: ChannelDocument[];
}): ChannelDocument;
export declare function buildChannelDocumentVersionRecord(input: {
    id: string;
    documentId: string;
    contentMarkdown: string;
    contentJson?: ChannelDocumentJsonContent;
    summary: string;
    createdBy: string;
    createdByType: ChannelDocumentEditorType;
    triggerType: ChannelDocumentTriggerType;
    sourceMessageId?: string;
    sourceAttachmentId?: string;
    sourceAttachmentStoredPath?: string;
    sourceTaskQueueId?: string;
    createdAt: string;
}): ChannelDocumentVersion;
export declare function normalizeChannelDocuments(documents: AgentSpaceState["channelDocuments"] | undefined, fallback: AgentSpaceState["channelDocuments"]): AgentSpaceState["channelDocuments"];
export declare function normalizeChannelDocument(document: unknown): ChannelDocument | null;
export declare function normalizeExternalSheetOperationRuns(runs: AgentSpaceState["externalSheetOperationRuns"] | undefined, fallback: AgentSpaceState["externalSheetOperationRuns"], documents: ChannelDocument[]): AgentSpaceState["externalSheetOperationRuns"];
export declare function normalizeExternalSheetOperationRun(run: unknown): ExternalSheetOperationRun | null;
export declare function normalizeChannelDocumentVersions(versions: AgentSpaceState["channelDocumentVersions"] | undefined, fallback: AgentSpaceState["channelDocumentVersions"], documents: ChannelDocument[]): AgentSpaceState["channelDocumentVersions"];
export declare function normalizeChannelDocumentVersion(version: unknown): ChannelDocumentVersion | null;
export declare function sortChannelDocuments(documents: ChannelDocument[]): ChannelDocument[];
export declare function summarizeChannelDocument(contentMarkdown: string, explicitSummary?: string): string;
export declare function ensureUniqueChannelDocumentSlug(documents: ChannelDocument[], channelName: string, title: string, currentDocumentId?: string): string;
